version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: eggcatcher
      POSTGRES_PASSWORD: fimoz
      POSTGRES_DB: egg_catcher
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  postgres-data: